[tool.ruff]
exclude = [
    ".env",
    ".venv",
    "**/migrations/**",
]
line-length = 119

[tool.ruff.lint]
ignore = [
    "E501",  # line too long
    "F403",  # 'from module import *' used; unable to detect undefined names
    "E701",  # multiple statements on one line (colon)
    "F401",  # module imported but unused
]
select = [
    "I",
    "E",
    "F",
    "W",
]
