# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 08:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_picture', '0002_auto_20151018_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_picture_picture', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
