# Generated by Django 4.1.8 on 2023-05-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0035_alter_cmsplugin_id_alter_globalpagepermission_id_and_more'),
        ('djangocms_picture', '0011_auto_20190314_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='%(app_label)s_%(class)s', serialize=False, to='cms.cmsplugin'),
        ),
    ]
