# Generated by Django 3.2 on 2022-05-04 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('djangocms_picture', '0011_auto_20190314_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='alternative_format_webp',
            field=models.CharField(choices=[('inherit', 'Default'), ('yes', 'Yes'), ('no', 'No')], default='inherit', help_text='Generate an alternative version of picture in .webp format. The browser will use it if supported.', max_length=7, verbose_name='Generate WebP version'),
        ),
        migrations.AddField(
            model_name='picture',
            name='large_screen_picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image (large screen)'),
        ),
        migrations.AddField(
            model_name='picture',
            name='large_screen_viewport_width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='This help even more the browser to choose the best image to display based on the expected image width on screen', null=True, verbose_name='Approximate image display width in percent of a large screen width (%)'),
        ),
        migrations.AddField(
            model_name='picture',
            name='medium_screen_picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.FILER_IMAGE_MODEL, verbose_name='Image (medium screen)'),
        ),
        migrations.AddField(
            model_name='picture',
            name='medium_screen_viewport_width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='This help even more the browser to choose the best image to display based on the expected image width on screen', null=True, verbose_name='Approximate image display width in percent of a medium screen width (%)'),
        ),
        migrations.AddField(
            model_name='picture',
            name='small_screen_viewport_width',
            field=models.PositiveSmallIntegerField(blank=True, help_text='This help even more the browser to choose the best image to display based on the expected image width on screen', null=True, verbose_name='Approximate image display width in percent of a small screen width (%)'),
        ),
    ]
